#!/usr/bin/env bash
# Configure Nginx to listen on port 80 and serve "Hello World!"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
