#!/usr/bin/env bash
# Short script to fix Nginx not listening on port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
