#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Modify nginx.conf to change user to nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Modify nginx.conf to listen on port 8080 on all IPs
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2

# Restart Nginx to apply changes
sudo -u nginx service nginx start
